import fs from "node:fs"
import path from "node:path"
import { execFileSync } from "node:child_process"
import { validateTask, validateResult } from "../validation/schema-validator.js"
import { OwnershipTracker } from "../policies/ownership.js"
import { containsSensitiveData } from "../logging/sanitizer.js"
import { GitChangeDetector } from "./git-detector.js"

import { VerificationRunner, VerificationResult } from "../verification/runner.js"
import type { TrustedDopplerClient } from "../doppler/client.js"

export interface FinalizerConfig {
  taskPath: string
  resultPath: string
  workspaceRoot: string
  dryRun?: boolean
  workflowRunId?: string
  targetToken?: string
  targetRemote?: string
  customVerificationProfiles?: Record<string, string>
  verificationTimeoutMs?: number
  reportOutputPath?: string
  createPr?: boolean
  fetchFn?: typeof fetch
  committerName?: string
  committerEmail?: string
  dopplerClient?: TrustedDopplerClient
}

export interface FinalizerReport {
  success: boolean
  dryRun: boolean
  pushed: boolean
  branchName: string
  error?: string
  commitSha?: string
  prUrl?: string
  trustedVerification?: VerificationResult
  authoritativeChangedPaths?: string[]
}

export class Finalizer {
  private task: any
  private result: any
  private dryRun: boolean
  private workflowRunId: string
  private workspaceRoot: string
  private targetToken?: string

  constructor(private config: FinalizerConfig) {
    this.dryRun = config.dryRun ?? true
    this.workflowRunId = config.workflowRunId || "manual"
    this.workspaceRoot = path.resolve(config.workspaceRoot)
    this.targetToken = config.targetToken

    this.loadAndValidate()
  }

  private loadAndValidate() {
    if (!fs.existsSync(this.config.taskPath)) {
      throw new Error(`Task file not found: ${this.config.taskPath}`)
    }
    if (!fs.existsSync(this.config.resultPath)) {
      throw new Error(`Result file not found: ${this.config.resultPath}`)
    }

    const taskRaw = fs.readFileSync(this.config.taskPath, "utf-8")
    this.task = JSON.parse(taskRaw)
    const taskValidation = validateTask(this.task)
    if (!taskValidation.valid) {
      throw new Error(`Invalid task manifest: ${taskValidation.errors?.join("; ")}`)
    }

    const resultRaw = fs.readFileSync(this.config.resultPath, "utf-8")
    this.result = JSON.parse(resultRaw)
    const resultValidation = validateResult(this.result)
    if (!resultValidation.valid) {
      throw new Error(`Invalid result schema: ${resultValidation.errors?.join("; ")}`)
    }
  }

  public static formatBranchName(runId: string, taskId: string): string {
    const cleanRunId = runId.replace(/[^a-zA-Z0-9-]/g, "")
    const cleanTaskId = taskId.replace(/[^a-zA-Z0-9-]/g, "-")
    return `swarm/${cleanRunId}/${cleanTaskId}`
  }

  public static formatPrBody(task: any, result: any): string {
    const lines = [
      `## Swarm Lane Execution: ${task.id}`,
      "",
      `### Metadata`,
      `- **Task ID:** ${task.id}`,
      `- **Role:** \`${task.role}\``,
      `- **Base SHA:** \`${task.base_sha}\``,
      `- **Status:** ${result.status}`,
      `- **Model Used:** \`${result.model_used}\``,
      `- **Tests Passed:** ${result.test_summary.passed}`,
      `- **Tests Failed:** ${result.test_summary.failed}`,
      `- **Policy Violations:** ${result.policy_violations.length}`,
      "",
      `### Objectives`,
      ...task.objectives.map((obj: string) => `- [x] ${obj}`),
      "",
      `### Verification Summary`,
      ...result.verification_results.map((vr: any) => `- \`${vr.profile}\`: exit code ${vr.exit_code} (${vr.passed ? "PASSED" : "FAILED"})`),
      "",
      `> Automated PR generated by OTONOM Swarm Finalizer. Raw diffs, source snippets, and credentials are intentionally excluded for public repository safety.`
    ]
    return lines.join("\n")
  }

  public async execute(): Promise<FinalizerReport> {
    const branchName = Finalizer.formatBranchName(this.workflowRunId, this.task.id)

    // 1. Verify Result Status
    if (this.result.status !== "PASS") {
      return {
        success: false,
        dryRun: this.dryRun,
        pushed: false,
        branchName,
        error: `Result status is not PASS (received: ${this.result.status})`
      }
    }

    // 2. Authoritative Git Change Detection & Reconciliation
    const gitDetector = new GitChangeDetector({
      workspaceRoot: this.workspaceRoot,
      baseSha: this.task.base_sha
    })

    const reconciliation = gitDetector.reconcileWithReported(this.result.changed_paths)
    if (!reconciliation.valid) {
      return {
        success: false,
        dryRun: this.dryRun,
        pushed: false,
        branchName,
        error: reconciliation.error
      }
    }

    const changeSummary = gitDetector.detectChanges()
    const allPathsToVerifyOwnership = new Set([
      ...changeSummary.actualChangedPaths,
      ...this.result.changed_paths
    ])
    // Also include old paths from renames
    for (const pair of changeSummary.renamePairs) {
      allPathsToVerifyOwnership.add(pair.oldPath)
      allPathsToVerifyOwnership.add(pair.newPath)
    }

    // 3. Enforce Ownership on Authoritative Git Paths
    const tracker = new OwnershipTracker({
      allowedWritePaths: this.task.allowed_write_paths,
      forbiddenWritePaths: this.task.forbidden_write_paths || []
    })

    for (const changedPath of allPathsToVerifyOwnership) {
      const check = tracker.recordEdit(changedPath)
      if (!check.allowed) {
        return {
          success: false,
          dryRun: this.dryRun,
          pushed: false,
          branchName,
          error: `Ownership violation on changed path: ${changedPath} (${check.violation?.policy})`
        }
      }
    }

    // 4. Secret Scan check on authoritative paths and file contents
    for (const p of allPathsToVerifyOwnership) {
      if (containsSensitiveData(p)) {
        return {
          success: false,
          dryRun: this.dryRun,
          pushed: false,
          branchName,
          error: `Secret scan violation: sensitive token detected in path ${p}`
        }
      }
      const fullPath = path.join(this.workspaceRoot, p)
      if (fs.existsSync(fullPath)) {
        const stat = fs.lstatSync(fullPath)
        if (stat.isFile() && stat.size < 5 * 1024 * 1024) {
          const content = fs.readFileSync(fullPath, "utf-8")
          if (containsSensitiveData(content)) {
            return {
              success: false,
              dryRun: this.dryRun,
              pushed: false,
              branchName,
              error: `Secret scan violation: sensitive token detected in file content of ${p}`
            }
          }
        }
      }
    }

    // 5. Trusted Independent Verification Execution
    const profileName = this.task.verification_profile || "lane"
    const verifier = new VerificationRunner({
      cwd: this.workspaceRoot,
      customProfiles: this.config.customVerificationProfiles,
      timeoutMs: this.config.verificationTimeoutMs
    })

    let trustedVerification: VerificationResult
    try {
      trustedVerification = await verifier.runProfile(profileName, this.config.verificationTimeoutMs)
    } catch (err: any) {
      const failedReport: FinalizerReport = {
        success: false,
        dryRun: this.dryRun,
        pushed: false,
        branchName,
        error: `Independent verification execution failed: ${err.message}`,
        authoritativeChangedPaths: changeSummary.actualChangedPaths
      }
      this.writeReport(failedReport)
      return failedReport
    }

    if (!trustedVerification.passed || trustedVerification.exit_code !== 0) {
      const failedReport: FinalizerReport = {
        success: false,
        dryRun: this.dryRun,
        pushed: false,
        branchName,
        error: `Independent verification failed for profile '${profileName}': exit code ${trustedVerification.exit_code}`,
        trustedVerification,
        authoritativeChangedPaths: changeSummary.actualChangedPaths
      }
      this.writeReport(failedReport)
      return failedReport
    }

    // 6. In Dry Run Mode: complete without git push / PR
    if (this.dryRun) {
      const successReport: FinalizerReport = {
        success: true,
        dryRun: true,
        pushed: false,
        branchName,
        trustedVerification,
        authoritativeChangedPaths: changeSummary.actualChangedPaths
      }
      this.writeReport(successReport)
      return successReport
    }

    // 7. In Real Mode: Write token is introduced strictly here
    if (!this.targetToken && this.config.dopplerClient) {
      const finalizerConfig = this.config.dopplerClient.getFinalizerConfig()
      this.targetToken = finalizerConfig.targetWriteToken
      if (!this.config.committerName) {
        this.config.committerName = finalizerConfig.committerName
      }
      if (!this.config.committerEmail) {
        this.config.committerEmail = finalizerConfig.committerEmail
      }
    }

    if (!this.targetToken) {
      const tokenReport: FinalizerReport = {
        success: false,
        dryRun: false,
        pushed: false,
        branchName,
        error: "Target repository write credentials not configured for finalizer push",
        trustedVerification,
        authoritativeChangedPaths: changeSummary.actualChangedPaths
      }
      this.writeReport(tokenReport)
      return tokenReport
    }

    // Defensive check: NEVER push to protected main or master branches
    this.validatePushBranch(branchName)

    // Verify task base SHA exists in repository history
    try {
      execFileSync("git", ["cat-file", "-e", `${this.task.base_sha}^{commit}`], {
        cwd: this.workspaceRoot,
        stdio: "ignore"
      })
    } catch {
      const shaReport: FinalizerReport = {
        success: false,
        dryRun: false,
        pushed: false,
        branchName,
        error: `Base SHA mismatch: commit ${this.task.base_sha} does not exist in workspace history`,
        trustedVerification,
        authoritativeChangedPaths: changeSummary.actualChangedPaths
      }
      this.writeReport(shaReport)
      return shaReport
    }

    // Stage ONLY actual validated changed paths (core.hooksPath=/dev/null ensures hooks are bypassed)
    for (const p of changeSummary.actualChangedPaths) {
      execFileSync("git", ["-c", "core.hooksPath=/dev/null", "add", p], {
        cwd: this.workspaceRoot,
        stdio: "ignore"
      })
    }

    // Commit changes safely if index is modified
    const diffCached = execFileSync("git", ["diff", "--cached", "--name-only"], {
      cwd: this.workspaceRoot,
      encoding: "utf-8"
    }).trim()

    const committerName = this.config.committerName || "OTONOM Swarm Worker"
    const committerEmail = this.config.committerEmail || "worker@otonom.internal"

    if (diffCached.length > 0) {
      execFileSync(
        "git",
        [
          "-c", "core.hooksPath=/dev/null",
          "-c", `user.name=${committerName}`,
          "-c", `user.email=${committerEmail}`,
          "commit",
          "-m", `swarm(${this.task.id}): automated lane completion`
        ],
        {
          cwd: this.workspaceRoot,
          env: {
            ...process.env,
            GIT_TERMINAL_PROMPT: "0"
          },
          stdio: "ignore"
        }
      )
    }

    const commitSha = execFileSync("git", ["rev-parse", "HEAD"], {
      cwd: this.workspaceRoot,
      encoding: "utf-8"
    }).trim()

    // Push to target remote without --force, bypassing hooks and without leaking tokens to git config
    const targetRemote = this.config.targetRemote || "origin"
    const pushArgs = [
      "-c", "core.hooksPath=/dev/null",
      "-c", "credential.helper="
    ]
    if (this.targetToken) {
      const authHeader = `AUTHORIZATION: basic ${Buffer.from(`x-access-token:${this.targetToken}`).toString("base64")}`
      pushArgs.push("-c", `http.https://github.com/.extraheader=${authHeader}`)
    }
    pushArgs.push("push", targetRemote, `HEAD:refs/heads/${branchName}`)

    try {
      execFileSync(
        "git",
        pushArgs,
        {
          cwd: this.workspaceRoot,
          env: {
            ...process.env,
            GIT_TERMINAL_PROMPT: "0",
            GIT_ASKPASS: ""
          },
          stdio: "ignore"
        }
      )
    } catch (pushErr: any) {
      const pushFailedReport: FinalizerReport = {
        success: false,
        dryRun: false,
        pushed: false,
        branchName,
        commitSha,
        error: `Git push failed: ${pushErr.message}`,
        trustedVerification,
        authoritativeChangedPaths: changeSummary.actualChangedPaths
      }
      this.writeReport(pushFailedReport)
      return pushFailedReport
    }

    let prUrl: string | undefined
    if (this.config.createPr) {
      try {
        prUrl = await this.createOrFindDraftPr(branchName, commitSha)
      } catch (prErr: any) {
        const prFailedReport: FinalizerReport = {
          success: false,
          dryRun: false,
          pushed: true,
          branchName,
          commitSha,
          error: `PR creation failed: ${prErr.message}`,
          trustedVerification,
          authoritativeChangedPaths: changeSummary.actualChangedPaths
        }
        this.writeReport(prFailedReport)
        return prFailedReport
      }
    }

    const realReport: FinalizerReport = {
      success: true,
      dryRun: false,
      pushed: true,
      branchName,
      commitSha,
      prUrl,
      trustedVerification,
      authoritativeChangedPaths: changeSummary.actualChangedPaths
    }
    this.writeReport(realReport)
    return realReport
  }

  private async createOrFindDraftPr(branchName: string, commitSha: string): Promise<string> {
    const fetchImpl = this.config.fetchFn || fetch
    const repoFullName = this.task.source_repository || "oaslananka/otonom"
    const [owner, repo] = repoFullName.split("/")
    const targetBranch = this.task.base_branch || "main"

    const headers: Record<string, string> = {
      "Accept": "application/vnd.github+json",
      "User-Agent": "otonom-worker-finalizer",
      "X-GitHub-Api-Version": "2022-11-28"
    }
    if (this.targetToken) {
      headers["Authorization"] = `Bearer ${this.targetToken}`
    }

    // 1. Idempotency: Check if PR already exists for head branch
    const queryUrl = `https://api.github.com/repos/${owner}/${repo}/pulls?head=${owner}:${branchName}&state=all`
    const listRes = await fetchImpl(queryUrl, { headers })
    if (listRes.ok) {
      const list = await listRes.json()
      if (Array.isArray(list) && list.length > 0) {
        const existing = list[0]
        console.log(`[Finalizer] Existing PR found: ${existing.html_url} (#${existing.number})`)
        return existing.html_url
      }
    }

    // 2. Create new Draft PR
    const createUrl = `https://api.github.com/repos/${owner}/${repo}/pulls`
    const prBody = Finalizer.formatPrBody(this.task, this.result)
    const createRes = await fetchImpl(createUrl, {
      method: "POST",
      headers: {
        ...headers,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        title: `[SWARM SMOKE] Validate private OpenCode agent pipeline`,
        head: branchName,
        base: targetBranch,
        body: prBody,
        draft: true
      })
    })

    if (!createRes.ok) {
      const errText = await createRes.text()
      throw new Error(`GitHub API error (${createRes.status}): ${errText}`)
    }

    const created = await createRes.json()
    console.log(`[Finalizer] Draft PR created successfully: ${created.html_url} (#${created.number})`)
    return created.html_url
  }

  public validatePushBranch(branchName: string): void {
    const normalized = branchName.trim().toLowerCase()
    if (
      normalized === "main" ||
      normalized === "master" ||
      normalized === "refs/heads/main" ||
      normalized === "refs/heads/master" ||
      normalized.endsWith("/main") ||
      normalized.endsWith("/master")
    ) {
      throw new Error(`Security violation: Refusing to push to protected main/master branch: '${branchName}'`)
    }
  }

  private writeReport(report: FinalizerReport) {
    if (this.config.reportOutputPath) {
      try {
        const outDir = path.dirname(this.config.reportOutputPath)
        fs.mkdirSync(outDir, { recursive: true })
        fs.writeFileSync(this.config.reportOutputPath, JSON.stringify(report, null, 2))
      } catch {
        // Log/ignore report write error
      }
    }
  }
}
