import fs from "node:fs"
import path from "node:path"
import { validateTask, validateResult } from "../validation/schema-validator.js"
import { OwnershipTracker } from "../policies/ownership.js"
import { containsSensitiveData } from "../logging/sanitizer.js"

export interface FinalizerConfig {
  taskPath: string
  resultPath: string
  workspaceRoot: string
  dryRun?: boolean
  workflowRunId?: string
  targetToken?: string
}

export interface FinalizerReport {
  success: boolean
  dryRun: boolean
  pushed: boolean
  branchName: string
  error?: string
  commitSha?: string
  prUrl?: string
}

export class Finalizer {
  private task: any
  private result: any
  private dryRun: boolean
  private workflowRunId: string
  private workspaceRoot: string
  private targetToken?: string

  constructor(private config: FinalizerConfig) {
    this.dryRun = config.dryRun ?? true
    this.workflowRunId = config.workflowRunId || "manual"
    this.workspaceRoot = path.resolve(config.workspaceRoot)
    this.targetToken = config.targetToken

    this.loadAndValidate()
  }

  private loadAndValidate() {
    if (!fs.existsSync(this.config.taskPath)) {
      throw new Error(`Task file not found: ${this.config.taskPath}`)
    }
    if (!fs.existsSync(this.config.resultPath)) {
      throw new Error(`Result file not found: ${this.config.resultPath}`)
    }

    const taskRaw = fs.readFileSync(this.config.taskPath, "utf-8")
    this.task = JSON.parse(taskRaw)
    const taskValidation = validateTask(this.task)
    if (!taskValidation.valid) {
      throw new Error(`Invalid task manifest: ${taskValidation.errors?.join("; ")}`)
    }

    const resultRaw = fs.readFileSync(this.config.resultPath, "utf-8")
    this.result = JSON.parse(resultRaw)
    const resultValidation = validateResult(this.result)
    if (!resultValidation.valid) {
      throw new Error(`Invalid result schema: ${resultValidation.errors?.join("; ")}`)
    }
  }

  public static formatBranchName(runId: string, taskId: string): string {
    const cleanRunId = runId.replace(/[^a-zA-Z0-9-]/g, "")
    const cleanTaskId = taskId.replace(/[^a-zA-Z0-9-]/g, "-")
    return `swarm/${cleanRunId}/${cleanTaskId}`
  }

  public static formatPrBody(task: any, result: any): string {
    const lines = [
      `## Swarm Lane Execution: ${task.id}`,
      "",
      `### Metadata`,
      `- **Task ID:** ${task.id}`,
      `- **Role:** \`${task.role}\``,
      `- **Base SHA:** \`${task.base_sha}\``,
      `- **Status:** ${result.status}`,
      `- **Model Used:** \`${result.model_used}\``,
      `- **Tests Passed:** ${result.test_summary.passed}`,
      `- **Tests Failed:** ${result.test_summary.failed}`,
      `- **Policy Violations:** ${result.policy_violations.length}`,
      "",
      `### Objectives`,
      ...task.objectives.map((obj: string) => `- [x] ${obj}`),
      "",
      `### Verification Summary`,
      ...result.verification_results.map((vr: any) => `- \`${vr.profile}\`: exit code ${vr.exit_code} (${vr.passed ? "PASSED" : "FAILED"})`),
      "",
      `> Automated PR generated by OTONOM Swarm Finalizer. Raw diffs, source snippets, and credentials are intentionally excluded for public repository safety.`
    ]
    return lines.join("\n")
  }

  public async execute(): Promise<FinalizerReport> {
    const branchName = Finalizer.formatBranchName(this.workflowRunId, this.task.id)

    // 1. Verify Result Status
    if (this.result.status !== "PASS") {
      return {
        success: false,
        dryRun: this.dryRun,
        pushed: false,
        branchName,
        error: `Result status is not PASS (received: ${this.result.status})`
      }
    }

    // 2. Enforce Ownership
    const tracker = new OwnershipTracker({
      allowedWritePaths: this.task.allowed_write_paths,
      forbiddenWritePaths: this.task.forbidden_write_paths || []
    })

    for (const changedPath of this.result.changed_paths) {
      const check = tracker.recordEdit(changedPath)
      if (!check.allowed) {
        return {
          success: false,
          dryRun: this.dryRun,
          pushed: false,
          branchName,
          error: `Ownership violation on changed path: ${changedPath} (${check.violation?.policy})`
        }
      }
    }

    // 3. Secret Scan check on changed path list and summaries
    for (const p of this.result.changed_paths) {
      if (containsSensitiveData(p)) {
        return {
          success: false,
          dryRun: this.dryRun,
          pushed: false,
          branchName,
          error: `Secret scan violation: sensitive token detected in path ${p}`
        }
      }
    }

    // 4. Verify Mechanical Evidence
    const hasPassingVerification = this.result.verification_results.some((v: any) => v.passed && v.exit_code === 0)
    if (!hasPassingVerification) {
      return {
        success: false,
        dryRun: this.dryRun,
        pushed: false,
        branchName,
        error: "No successful verification result recorded in result.json"
      }
    }

    // 5. In Dry Run Mode: complete without git push / PR
    if (this.dryRun) {
      return {
        success: true,
        dryRun: true,
        pushed: false,
        branchName
      }
    }

    // 6. In Real Mode: Write token is introduced strictly here
    if (!this.targetToken) {
      return {
        success: false,
        dryRun: false,
        pushed: false,
        branchName,
        error: "Target repository write credentials not configured for finalizer push"
      }
    }

    // Target push and PR creation would happen here in Phase 2
    return {
      success: true,
      dryRun: false,
      pushed: true,
      branchName
    }
  }
}
